In [1]:
import pandas as pd 
import numpy as np 

1)Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [2]:
def gen_vander_matrix(ipmat, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipmat for i in range(n)]).reshape(ipmat.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipmat for i in range(n)]).reshape(ipmat.size,n)
    
    return op_matx

In [3]:
inputmatx = np.array([4,5,6])
no_col_opmat = 2
op_matx_dec_order = gen_vander_matrix(inputmatx,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputmatx,no_col_opmat,True)

print("The input array is:",inputmatx,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [4 5 6] 

Number of columns in output matrix should be: 2 

Vander matrix of the input array in decreasing order of powers:

 [[4 1]
 [5 1]
 [6 1]] 

Vander matrix of the input array in increasing order of powers:

 [[1 4]
 [1 5]
 [1 6]] 











Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values. Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

Note: Solution submitted via github must contain all the detailed steps.

3.Output

This assignment consists of 200 marks and needs to be submitted in the upcoming session for evaluation.



In [4]:
def moving_average(a, k=3) :
    ret = np.cumsum(a, dtype=float)
    ret[k:] = ret[k:] - ret[:-k]
    return ret[k - 1:] / k

moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])